apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: just-task-it
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: ""
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: just-task-it-service
                port:
                  number: 80