apiVersion: v1
kind: Service
metadata:
  name: just-task-it-loadbalancer
  namespace: just-task-it
  labels:
    app: just-task-it
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: just-task-it
  ports:
  - name: http
    port: 80
    targetPort: 3002
    protocol: TCP