apiVersion: v1
kind: Service
metadata:
  name: just-task-it-service
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: just-task-it
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
