apiVersion: v1
kind: Service
metadata:
  name: just-task-it-service
  labels:
    app: just-task-it
spec:
  type: LoadBalancer
  selector:
    app: just-task-it
  ports:
    - name: http
      port: 80
      targetPort: 3002
      protocol: TCP
